castcrews/urls.py
from django.conf.urls import url
from django.views.generic import ListView, DetailView, TemplateView

from castcrews.models import Film, Person, Role


urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='castcrews/index.html'
    )),

    url(r'^films/$', ListView.as_view(
        model=Film,
    ), name='browse-films'),
    url(r'^people/$', ListView.as_view(
        model=Person,
    ), name='browse-people'),
    url(r'^roles/$', ListView.as_view(
        model=Role,
    ), name='browse-roles'),


    url(r'^films/(?P<pk>\d+)/$', DetailView.as_view(
        model=Film,
    ), name='show-film'),
    url(r'^people/(?P<pk>\d+)/$', DetailView.as_view(
        model=Person
    ), name='show-person'),
    url(r'^roles/(?P<pk>\d+)/$', DetailView.as_view(
        model=Role,
    ), name='show-role'),
]

lmastracker/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('castcrews.urls')),
]

castcrews/models.py
from django.db import models


class Film(models.Model):
    title = models.CharField(max_length=255)
    upload_date = models.DateField()


class Role(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Billing(models.Model):
    film = models.ForeignKey('Film')
    person = models.ForeignKey('Person')
    role = models.ForeignKey('Role')
    extra = models.CharField(max_length=255, blank=True, null=True)  # Created to hold the character name for actor billings

castcrews/templates/castcrews/base.html
<html>
<head>
<title>LMAS Browser</title>
</head>

<body>
<h2><a href="/">LMAS Film Browser</a></h2>
{% block content %}

{% endblock %}
</body>
</html>

castcrews/templates/castcrews/film_detail.html
{% extends 'castcrews/base.html' %}

{% block content %}
<h2>{{ film.title }}</h2>

<h3>Cast</h3>

<ul>
{% for billing in film.billing_set.all %}
{% ifequal billing.role.name 'Actor' %}
    <li><a href="{% url "show-role" pk=billing.role.pk %}">
        {% if billing.extra %}{{ billing.extra }}{% else %}Actor{% endif %}</a>:
        <a href="{% url "show-person" billing.person.pk %}">{{ billing.person.name }}</a>
    </li>
{% endifequal %}
{% endfor %}
</ul>

<h3>Crew</h3>
<ul>
{% for billing in film.billing_set.all %}
{% ifnotequal billing.role.name 'Actor' %}
    <li><a href="{% url "show-role" billing.role.id %}">{{ billing.role.name }}</a>:
        <a href="{% url "show-person" billing.person.pk %}">{{ billing.person.name }}</a>
    </li>
{% endifnotequal %}
{% endfor %}
</ul>

{% endblock %}

castcrews/templates/castcrews/film_list.html
{% extends 'castcrews/base.html' %}

{% block content %}
<h2>Films</h2>
<ul>
{% for film in film_list %}
<li><a href="{% url "show-film" pk=film.id %}">{{ film.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

castcrews/templates/castcrews/index.html
{% extends 'castcrews/base.html' %}

{% block content %}

<p>A thingummy for finding out who did what on LMAS films.</p>

<p><a href="{% url 'browse-films' %}">Browse films</a></p>
<p><a href="{% url 'browse-people' %}">Browse people</a></p>
<p><a href="{% url 'browse-roles' %}">Browse roles</a></p>
{% endblock %}

castcrews/templates/castcrews/person_detail.html
{% extends 'castcrews/base.html' %}

{% block content %}
<h2>{{ person.name }}</h2>

<h3>Cast</h3>

<ul>
{% for billing in person.billing_set.all %}
{% ifequal billing.role.name 'Actor' %}
    <li>
    <a href="{% url "show-film" billing.film.pk %}">{{ billing.film.title }}</a>:
    <a href="{% url "show-role" billing.role.pk %}">{% if billing.extra %}{{ billing.extra }}{% else %}Actor{% endif %}</a>
    </li>
{% endifequal %}
{% endfor %}
</ul>

<h3>Crew</h3>
<ul>
{% for billing in person.billing_set.all %}
{% ifnotequal billing.role.name 'Actor' %}
    <li>
        <a href="{% url "show-film" billing.film.pk %}">{{ billing.film.title }}</a>:
        <a href="{% url "show-role" billing.role.id %}">{{ billing.role.name }}</a>
    </li>
{% endifnotequal %}
{% endfor %}
</ul>

{% endblock %}

castcrews/templates/castcrews/person_list.html
{% extends 'castcrews/base.html' %}

{% block content %}
<h2>People</h2>
<ul>
{% for person in person_list %}
<li><a href="{% url "show-person" pk=person.id %}">{{ person.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

castcrews/templates/castcrews/role_detail.html
{% extends 'castcrews/base.html' %}

{% block content %}
<h2>{{ role.name }}</h2>

<ul>
{% for billing in role.billing_set.all %}
    <li>
        <a href="{% url "show-film" billing.film.pk %}">{{ billing.film.title }}</a>:
        <a href="{% url "show-person" billing.person.id %}">{{ billing.person.name }}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

castcrews/templates/castcrews/role_list.html
{% extends 'castcrews/base.html' %}

{% block content %}
<h2>Roles</h2>
<ul>
{% for role in role_list %}
<li><a href="{% url "show-role" pk=role.id %}">{{ role.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}